name: Test-Linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test --enable-test-discovery  --sanitize=thread
