name: Test-watchOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - '*'

jobs:
  watchOS:
    name: Build watchOS
    runs-on: macOS-latest
    env: 
      DEVELOPER_DIR: /Applications/Xcode_11.6.app/Contents/Developer
    strategy:
      matrix:
        destination: ["OS=6.2.1,name=Apple Watch Series 5 - 44mm"]
    steps:
      - uses: actions/checkout@v2
      - name: watchOS - ${{ matrix.destination }}
        run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -scheme Easing -destination "${{ matrix.destination }}" clean build | xcpretty
