name: Test-watchOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - '*'

jobs:
  tvOS:
    name: Test watchOS 
    runs-on: macOS-latest
    env: 
      DEVELOPER_DIR: /Applications/Xcode_11.6.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - name: Xcode watchOS
        run: set -o pipefail && xcodebuild build -scheme Easing -destination 'platform=watchOS Simulator,name=Apple Watch Series 5 - 44mm' ENABLE_TESTING_SEARCH_PATHS=YES | xcpretty -c
