name: Test-tvOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - '*'

jobs:
  tvOS:
    name: Test tvOS 
    runs-on: macOS-latest
    env: 
      DEVELOPER_DIR: /Applications/Xcode_11.6.app/Contents/Developer
    strategy:
      matrix:
        destination: ["OS=13.4,name=Apple TV 4K"]
    steps:
      - uses: actions/checkout@v2
      - name: tvOS - ${{ matrix.destination }}
        run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -scheme Easing -destination "${{ matrix.destination }}" clean test | xcpretty
